uwsgi:
  socket: /app/{{cookiecutter.project_slug}}.sock
  chmod-socket: 666
  module: {{cookiecutter.project_slug}}.app
  enable-threads: true
  workers: 8
  virtualenv: env/
  logformat: {"service": "{{cookiecutter.project_slug}}", "ip": "%(addr)", "status": %(status), "method": "%(method)", "uri": "%(uri)", "duration": %(msecs)}
  req-logger: socket:{{cookiecutter.logstash_url}}:{{cookiecutter.logstash_request_port}}
  log-req-encoder: format ${msg}
  logger: socket:{{cookiecutter.logstash_url}}:{{cookiecutter.logstash_uwsgi_port}}
  log-req-encoder: json {"message": "${msg}"}
