uwsgi:
  socket: /app/{{cookiecutter.project_slug}}.sock
  chmod-socket: 666
  module: {{cookiecutter.project_slug}}.app
  enable-threads: true
  workers: 8
  virtualenv: env/
  logformat: %(addr) - %(status) - %(method) - %(uri) - %(msecs)ms
  req-logger: file:logs/requests.txt
  log-req-encoder: format ${strftime:%%Y-%%m-%%dT%%H:%%M:%%S} ${msgnl}
  logger: file:logs/uwsgi.txt
